### ISSUE TITLE
User guide: tensors and indices

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#112]
`docs/pages/user-guide/tensor-and-indices.md`

This is the first part of the user guide. The goal is to:
- Introduce the APIs to create tensors and indices
- !!! note: explain the 'abstract' nature of the tensors, i.e. they are **not** yet populated with concrete numbers yet.
- !!! note: explain the index identity logic: identities check is performed on UUIDs on a Python variable basis, not done on the 'symbol', which is merely for human visualization.

**Comment by campsd** [comment]
Here we should also talk about `initializers` and `conditions`
