### ISSUE TITLE
User guide: tensor expressions

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#113]
`docs/pages/user-guide/tsrex.md`

This is the second part of the user guide. Our goal here is to showcase how to express computations on tensors using either an indexless or Einstein-notation format.

!!! note
    Emphasize that FunFact adopts a lazy evaluation model, in contrast to the eager mode as enabled by default by PyTorch and JAX. Computation does not happen immediately until at `funfact.from_tsrex` or `funfact.factorize`.

Outline:
- Indexless expressions (mention this is basically the same as NumPy): elementwise operations (`+`, `-`, `*`, `/`), inner product (`@`), exponentiation (`**`), etc.
- Indxed expressions: this invokes the Einstein-summation convention where repeated indices are contracted/reduced.
  - `~` for explicitly disabling reduction
  - `*` for within-dimension outer product (i.e. Kronecker)
  - `>>` for transposition
  - repeated application of `[...]` leads to index renaming.
  - !!! note: explain the difference between `[...] >> [...]` and `[...][...]`.
- Query properties of the tensor expression: `ndim`, `shape` etc.

**Comment by campsd** [comment]
@yhtang Should we also talk about the math module (`ff.exp`,...) here? This can be used in a tensor expression. And how about the other semiring operations (`Viterbi`, ...) that can be used in the indexed expressions?
