### ISSUE TITLE
Library of semiring operators

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#13]
e.g. minplus, Viberti, etc.

**Comment by campsd** [comment]
Currently we have the binary operation `op` which is either multiplication, division, addition or subtraction. The reduction is always done by a summation over contracting indices. The standard `einsum` operation can be considered as a `SumProduct` contraction. We can now currently do: `SumProduct`, `SumDivision`, `SumSum`, `SumDifference`.

List of more possibilities:

**Binary operation:**

- Multiplication: `a * b`
- Division: `a / b`
- Sum: `a + b`
- Difference: `a - b`
- Max, min: `max(a,b)`, `min(a,b)`
- [Viterbi](https://bdusell.github.io/semiring-einsum/api.html): `log(exp(a) + exp(b))`
- ...

**Contraction:**

- Sum: `a + b` (Difference does not make sense for contraction?)
- Product `a * b` (Division does not make sense for contraction?)
- [Logspace einsum](https://bdusell.github.io/semiring-einsum/api.html): `log(exp(a) + exp(b))`
- [Viterbi](https://bdusell.github.io/semiring-einsum/api.html): `(max(a,b), argmax(a,b))`

**Comment by campsd** [comment]
Reopening this as we need to update this functionality to the latest code specification and add some test cases to help us keep it up to date during future development.

**Comment by yhtang** [comment]
Make sense. In my latest PR #146, I did modernize the semiring tsrex creation but did not implement any tests.
