### ISSUE TITLE
Backend for Kronecker product operations

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#34]
This is a follow-up to #33. It seems like both the index propagator, slice propagator, and einop method needs to be updated accordingly. Meanwhile, given that there are now three types of indices (live, keep, and kron) in the einop operation, it might make sense to bypass the einspec procedure and directly use the live indices to carry out einop operations.

**Comment by campsd** [comment]
_Blow up_ Kron indices inside `einop` (using kronecker product with one vector).
