### ISSUE TITLE
Expand the set of optimizers and loss functions

### ISSUE THREAD

**Issue by campsd** [yhtang/FunFact#54]
We currently have the `Adam` optimizer and the `MSE (L2)` loss function.

We should add a few more options to the optimization library:

*Optimizers*

- RMSProp
- AdaGrad
- ... 

*Loss functions*
- L1 loss
- KL divergence
- ...

Additionally, we should allow the user to add a **penalty term** to the loss function to enforce (unitary) constraints.

**Comment by yhtang** [comment]
We might need to wrap up this issue as soon as possible, since:
1. it is blocking the demo & documentation of `factorize`.
2. it might fall out of sync with all the other changes, in particular the backend PR #75.

I thought we already have most of the parts, right? :smiling_imp:
