### ISSUE TITLE
Refactor package for v1.0 release

### ISSUE THREAD

**Issue by campsd** [yhtang/FunFact#55]
There are a few refactoring issues to resolve for the initial release.

Move all files to appropriate (new) modules:

- `_einop` should be moved from the `lang>interpreters` to `algorithm` module
- look into reorganizing the `optim` module
- `nn` neural network module
- rethink the interface to `Factorization` and the `factorize` function: 1) `fit` method for factorization, 2) add `vectorize` option, 3) `tol` convergence checking, ...
- ...

Expose all required functionality to the enduser: `Factorization`, `factorize`, `neural network`, ...

**Comment by yhtang** [comment]
We can make sure `Factorization` is accessible at the top level, and then this should eliminate the need for #32.

**Comment by yhtang** [comment]
Closing it now as its scope has been well exceeded.
