### ISSUE TITLE
Ambiguous semantics of the `.T` transposition syntax

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#60]
**Describe the bug**
Potnetial flaw in the `.T[...]`  transposition syntax:

When people write `$A^T_{ij}$`, they mean the (i, j)-th element of the transposition of A. Therefore, the Einstein notation `$A_{ij} \cdot A^T_{ij}$` means the inner product between A and its transposition.

In Funfact, however, if A is a tsrex with live indices `i, j`, then `A.T[i. j]` does nothing --- it merely means to reorder the live indices of A from `i, j` to `i, j`, so nothing happens.

This is because `.T` means **tranpose according to the following []** instead of directly creating a transposed tensor where the dimensions are reversed.

This could catch a user off-guard if they are trying to do a literal translation of some formula on paper to code using FunFact.

**On the other hand, with the Einstein notation, there is no need to use `.T` to obtain the transposition of a tensor for computation --- simply adjusting the order of the indices will do.** The only purpose of `.T` is to actually transpose the tensor in memory for storage purposes.

**To Reproduce**
```
i, j, k = ff.indices('i, j, k')
A = ff.tensor('A', 3, 3)
tsrex = A * A.T[j, k]  # expects to get $A \cdot A^T$, won't work
tsrex = A[i, j] * A[k, j]  # this works and computes A * A^T
```

**Discussion**

Is there a need to adjust this?

**Comment by yhtang** [comment]
Maybe it makes more sense to think of `.T` as a permutation matrix.

**Comment by campsd** [comment]
We also have the `>>` notation which also allows us to reorder the indices. Maybe `.T` is unnecessary as we can normally always handle it at the `ein` level except for trivial cases where you just want to transpose a tensor that didn't go through an `ein` operation.

**Comment by yhtang** [comment]
Makes sense. We can also extend the `>>` syntax to any tensor expression for handling transposition.
