### ISSUE TITLE
Zero dimensional tensors

### ISSUE THREAD

**Issue by campsd** [yhtang/FunFact#69]
For constant optimizable offsets in a tensor expression, we should add the support for zero-dimensional tensors.

An example use case and suggested syntax is given in the following RBF expression:
```Python
# RBF approximation, one instance
m, n = 24, 36
r = 8
u = ff.tensor('u', m, r)
v = ff.tensor('v', n, r)
a = ff.tensor('a', r)
b = ff.tensor('b')
i, j, k = ff.indices('i, j, k')
tsrex = a[k] * ff.exp(-(u[i, ~k] - v[j, ~k])**2) + b[:] # or b[...]
```

**Comment by yhtang** [comment]
Turns out the answer is only one step away: by simply permitting tensors to be indexed by `None` or `[]`, the rest of tsrex pipeline already supports 0th order tensors --- even initialization and vectorization works out of the box!
