### ISSUE TITLE
[BUG] `einop` does not work with the PyTorch backend

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#76]
**Describe the bug**
Our current `einop` implementation depends on `order='F'` of `numpy.transpose` or `jax.numpy.transpose`, which PyTorch does not implement. Simply removing the order specifier leads to incorrect results.

**To Reproduce**
```
ff.use('torch')
u = ff.tensor(np.arange(3))
v = ff.tensor(np.ones(4))
i = ff.index()
fac = Factorization(u[[*i]] * v[[*i]])
fac()
```

**Expected behavior**
`[0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2.]`

**Additional context**
This StackOverflow [answer](https://stackoverflow.com/a/63964246) provides a solution that is potentially slow. Also, I tried to directly cast the solution and ended up getting a single number instead of 12 elements.

**Comment by campsd** [comment]
I have identified the reason why `einop` reduces to the scalar `12` when using the `torch` backend. It happens in the reduction operation. The behavior of [`torch.sum`](https://pytorch.org/docs/stable/generated/torch.sum.html) is different from [`np.sum`](https://numpy.org/doc/stable/reference/generated/numpy.sum.html). 

Code snippet illustrates the issue:
```Python
import torch
import jax.numpy as jnp

a = torch.ones(4, 4)
print(a)
torch.sum(a, [])
# output: 16

b = jnp.ones([4,4])
print(b)
jnp.sum(b, [])
# output: 4x4 array of ones
```
