### ISSUE TITLE
[BUG] `dtype`  not used in tensor initializer.

### ISSUE THREAD

**Issue by yhtang** [yhtang/FunFact#84]
**Describe the bug**
The `LeafInitializer` interpreter has an optional argument `dtype` which defaults to `ab.float32`. However, it is not used by any of the primitives.

**Expected behavior**
The data type of the created tensor should be specified by this argument.

**Additional context**
Having `ab.float32` as the default value in the function signature causes very early import of the default backend. This is an undesired behavior. Since the initializer is very likely an internal tool used only by developers, I suggest we remove the default values.

**Comment by yhtang** [comment]
@campsd pointed out that this will be highly relevant to the quantum compilation application.

**Comment by campsd** [comment]
Collecting some thoughts and findings:

* [Gotcha #5](https://github.com/google/jax#current-gotchas) from JAX is something to take into account here. By default JAX only supports single precision
* [Complex single precision](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#complex-numbers-and-differentiation) appear to be fully supported
* [PyTorch](https://pytorch.org/docs/stable/complex_numbers.html) has full support

**Comment by yhtang** [comment]
> Gotcha #5 from JAX is something to take into account here. By default JAX only supports single precision

This seems quite manageable to me. We can insert the `JAX_ENABLE_X64=True` environment variable if, say, user do `ff.use('jax64')`.

**Comment by campsd** [comment]
I ran some tests and that seems to work. However, the environment variable has to set before JAX is loaded.

**Comment by yhtang** [comment]
> However, the environment variable has to set before JAX is loaded.

Can we add an `enable_complex=True/False`option to `backend.use` that auyomatically does this for the users?

**Comment by campsd** [comment]
> > However, the environment variable has to set before JAX is loaded.
> 
> Can we add an `enable_complex=True/False`option to `backend.use` that auyomatically does this for the users?

Yes, that could work. However it would have to be `enable_64bit=True/False`.

**Comment by yhtang** [comment]
> > > However, the environment variable has to set before JAX is loaded.
> > 
> > 
> > Can we add an `enable_complex=True/False`option to `backend.use` that auyomatically does this for the users?
> 
> Yes, that could work. However it would have to be `enable_64bit=True/False`.

Ah I see. My mind was still going with the complex number stuff. :joy: 

BTW this option mentioned on JAX docs seems better than the environment variable option:
```
# again, this only works on startup!
from jax.config import config
config.update("jax_enable_x64", True)
```
and we can also raise a warning if it was specified too late via the diagnostic mechanism mentioned on that page.

**Comment by yhtang** [comment]
Taken care of by #128.
